
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    networks:
      - iacom_net

  db:
    image: postgres:15.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - iacom_net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - iacom_net

  celery_worker:
    container_name: celery_worker
    image: "iacom_test-app:latest"
    entrypoint: /bin/sh -c "celery -A src.celery_worker.celery_app worker --pool=solo --loglevel=info"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
    networks:
      - iacom_net

  flower:
    container_name: flower
    image: "iacom_test-app:latest"
    entrypoint: /bin/sh -c "celery -A src.celery_worker.celery_app flower --port=5555"
    env_file:
      - .env
    ports:
      - "5556:5555"
    depends_on:
      - app
      - redis
      - celery_worker
    networks:
      - iacom_net

  migration:
    container_name: migration_dbmate
    env_file:
      - .env
    image: "iacom_test-app:latest"
    entrypoint: /bin/sh -c "dbmate wait && dbmate up"
    depends_on:
      - app
      - db
    networks:
      - iacom_net

volumes:
  db_data:

networks:
  default:
    driver: bridge
  iacom_net:
    driver: bridge
